# Generated by Django 2.2 on 2019-05-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vaccines',
            new_name='Vaccine',
        ),
    ]
