# Generated by Django 2.2 on 2019-05-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0002_auto_20190516_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
