# Generated by Django 2.2 on 2019-05-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0004_child'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Child',
            new_name='Children',
        ),
    ]
