# Generated by Django 2.2 on 2019-05-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0005_auto_20190516_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Children',
            new_name='Child',
        ),
    ]
