# Generated by Django 2.2 on 2019-05-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0007_auto_20190516_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50)),
                ('vaccinations', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='child',
            name='child_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
