# Generated by Django 2.2 on 2019-05-22 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0008_auto_20190516_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trak.Child'),
            preserve_default=False,
        ),
    ]
