# Generated by Django 2.2 on 2019-05-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0009_parent_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='parent_id',
            new_name='id_number',
        ),
        migrations.RemoveField(
            model_name='child',
            name='child_id',
        ),
    ]
