# Generated by Django 2.2 on 2019-05-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0012_auto_20190522_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
