# Generated by Django 2.2 on 2019-05-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0013_parent_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
