# Generated by Django 2.2 on 2019-06-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0014_auto_20190522_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
