# Generated by Django 2.2 on 2019-06-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0015_auto_20190613_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
