# Generated by Django 2.2 on 2019-06-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0016_auto_20190613_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('vaccinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trak.Vaccine')),
            ],
        ),
    ]
