# Generated by Django 2.2 on 2019-06-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0020_child_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='county',
            field=models.CharField(choices=[('mombasa', 'Mombasa'), ('nairobi', 'Nairobi'), ('nakuru', 'Nakuru')], max_length=20),
        ),
        migrations.DeleteModel(
            name='County',
        ),
    ]
