# Generated by Django 2.2 on 2019-06-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0021_auto_20190623_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='county',
            field=models.CharField(choices=[('Mombasa County', 'Mombasa'), ('Nairobi County', 'Nairobi'), ('Nakuru County', 'Nakuru')], max_length=20),
        ),
    ]
