# Generated by Django 2.2 on 2019-06-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0023_auto_20190625_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='county',
            field=models.CharField(choices=[('Mombasa County', 'Mombasa'), ('Kwale County', 'Kwale'), ('Kilifi County', 'Kilifi'), ('Tana River County', 'Tana River'), ('Lamu County', 'Lamu'), ('Taita Taveta County', 'Taita Taveta'), ('Garissa County', 'Garissa'), ('Wajir County', 'Wajir'), ('Mandera County', 'Mandera'), ('Marsabit County', 'Marsabit'), ('Isiolo County', 'Isiolo'), ('Meru County', 'Meru'), ('Tharaka Nithi County', 'Tharaka Nithi'), ('Embu County', 'Embu'), ('Kitui County', 'Kitui'), ('Machakos County', 'Machakos'), ('Makueni County', 'Makueni'), ('Nyandarua County', 'Nyandarua'), ('Nyeri County', 'Nyeri'), ('Kirinyaga County', 'Kirinyaga'), ("Murang'a County", "Murang'a"), ('Kiambu County', 'Kiambu'), ('Turkana County', 'Turkana'), ('West Pokot County', 'West Pokot'), ('Samburu County', 'Samburu'), ('Trans-Nzoia County', 'Trans-Nzoia'), ('Uasin Gishu County', 'Uasin Gishu'), ('Elgeyo Marakwet County', 'Elgeyo Marakwet'), ('Nandi County', 'Nandi'), ('Baringo County', 'Baringo'), ('Laikipia County', 'Laikipia'), ('Nakuru County', 'Nakuru'), ('Narok County', 'Narok'), ('Kajiado County', 'Kajiado'), ('Kericho County', 'kericho'), ('Bomet County', 'Bomet'), ('Kakamega County', 'Kakamega'), ('Vihiga County', 'Vihiga'), ('Bungoma County', 'Bungoma'), ('Busia County', 'Busia'), ('Siaya County', 'Siaya'), ('Kisumu County', 'Kisumu'), ('Homa Bay County', 'Homa Bay'), ('Migori County', 'Migori'), ('Kisii County', 'Kisii'), ('Nyamira County', 'Nyamira'), ('Nairobi County', 'Nairobi')], max_length=20),
        ),
    ]
