# Generated by Django 2.2 on 2019-06-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0024_auto_20190625_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
