# Generated by Django 2.2 on 2019-06-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '__first__'),
        ('trak', '0025_auto_20190625_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Child',
            new_name='Kid',
        ),
    ]
