# Generated by Django 2.2 on 2019-06-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0026_auto_20190626_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='county',
            field=models.CharField(max_length=20),
        ),
    ]
