# Generated by Django 2.2 on 2019-05-22 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0014_auto_20190522_0948'),
        ('schedule', '0002_auto_20190522_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trak.Vaccine'),
            preserve_default=False,
        ),
    ]
