# Generated by Django 2.2 on 2019-05-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='type',
            new_name='vaccine',
        ),
    ]
