# Generated by Django 2.2 on 2019-06-13 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20190613_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedules', to='trak.Vaccine'),
        ),
    ]
